targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generate import for all @injectable classes

      freezed:freezed:
        enabled: true

      json_serializable:
        enabled: true
